# Change this to change the name of the site in the browser tab
name: robogals
# This will show up as the description for the site on things such as google
description: Inspiring tomorrow's engineers, today.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  url_launcher: ^6.1.4
  youtube_player_iframe: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/level.json